### ISSUE TITLE
Unnecessary permissions on file open

### ISSUE THREAD

**Issue by aguerrieri** [victorjonsson/remote-tail#1]
on the server module, line 50, the log file is open with "r+" (read/write) permissions. This is unnecessary, and potentially dangerous, as there is no need to write to the file. In my case, it was forcing me to run the script as root to tail a file that was otherwise readable by my user.
IMHO, "r" should suffice.

**Comment by victorjonsson** [comment]
Yes, that was indeed unnecessary. Thanks for the pr!

**Comment by aguerrieri** [comment]
Thank you for writing such a useful module!
